{% set setup_data = load_setup_py_data() %}

package:
  name: conda_test
  version: {{ setup_data.version }}

source:
  git_url: https://github.com/blackbox-tech/conda_test.git
  git_rev: {{ setup_data.version }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pyyaml

test:
  imports:
    - conda_test
  source_files:
    - tests/test_*.py
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home:  https://github.com/blackbox-tech/conda_test
  license:  PROPRIETARY
